language: scala
dist: trusty
scala: 
  - 2.11.6
jdk: oraclejdk8

notifications:
  slack:
    - rooms:
      - makewonder:265Cpx92gIlDLezQWZqCVZog#ws-bots
      if: true

before_cache:
  # Cleanup the cached directories to avoid unnecessary cache updates
  - rm -fv $HOME/.ivy2/.sbt.ivy.lock
  - find $HOME/.ivy2/cache -name "ivydata-*.properties" -print -delete
  - find $HOME/.sbt        -name "*.lock"               -print -delete

cache:
  directories:
    - $HOME/.cache
    - $HOME/.ivy2/cache
    - $HOME/.sbt

script:
  - sbt compile
  - sbt test
